_target_: deepmc.models.ms_module.MOLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0002
  betas: [0.9, 0.999]

encoder_net:
  _target_: deepmc.models.components.MoCap_Solver.MO_enc
  num_layers: 2
  kernel_size: 15
  skeleton_dist: 2
  extra_conv: 0

decoder_net:
  _target_: deepmc.models.components.MoCap_Solver.MO_dec
  num_layers: 2
  kernel_size: 15
  skeleton_dist: 2
  extra_conv: 0

ts_encoder_ckpt_dir: ${paths.root_dir}/logs/train/runs/2022-07-24_10-17-20/checkpoints/epoch_99802.ckpt

fk: 
  _target_: deepmc.models.components.MoCap_Solver.Kinematics.ForwardKinematics
  topology: [0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 9, 12, 13, 14, 16, 17, 18, 19, 20, 21]

topology: [0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 9, 12, 13, 14, 16, 17, 18, 19, 20, 21]
data_dir: ${paths.data_dir}

beta_1: 2.5
beta_2: 1.0
beta_3: 100.0
beta_4: 5.0