_target_: deepmc.models.ms_module.TSLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0002
  betas: [0.9, 0.999]

encoder_net:
  _target_: deepmc.models.components.MoCap_Solver.TS_enc
  topology: [0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 9, 12, 13, 14, 16, 17, 18, 19, 20, 21]
  num_layers: 2
  skeleton_dist: 2

decoder_net:
  _target_: deepmc.models.components.MoCap_Solver.TS_dec
  topology: [0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 9, 12, 13, 14, 16, 17, 18, 19, 20, 21]
  num_layers: 2
  skeleton_dist: 2

topology: [0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 9, 12, 13, 14, 16, 17, 18, 19, 20, 21]
data_dir: ${paths.data_dir}