_target_: deepmc.datamodules.ms_datamodule.MCDataModule
data_dir: ${paths.data_dir}
batch_size: 256
topology: [0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 9, 12, 13, 14, 16, 17, 18, 19, 20, 21]
num_workers: 0
pin_memory: True
