_target_: deepmc.datamodules.ms_datamodule.oursDataModule
data_dir: ${paths.data_dir}
batch_size: 512
topology: [0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 9, 12, 13, 14, 16, 17, 18, 19, 20, 21]
mode: "msalign"
lazy: False
subset: 8
num_workers: 1
pin_memory: True
